# -*- coding: utf-8 -*-
"""EylemOykuAtalay_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168Pr5Hl6TiOaStrQpOpzTZ7YNrYdgm0Y

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is."""

#An algorithm is set of formulas for solving problems, making calculations and reach decisions. It is like a cooking recipe.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

#Brute-Force regular design approach involves direct computation based on the problem's statement and the definition of the concepts involved but it is uneffected when it comes to dealing with much more complex problems. Also it is not suitable for solving problems that have an hierachial structures and logical operations. But in algorithmic design, the algorithm will examine all possible ways to solve the problem and will pick the best solution. Also algorithmic design is much faster than Bruce-force method.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

#New approachs on design such as algorithmic design help us to make our work faster and also show us lots of possibilities. These kinds of approach can be used many different design areas. For example, people are using it on architecture to find best ways to make a building or just a furniture. In normal ways, finding the best possible solution and seeing the all possible ways are so much time consuming. With the help of algorithmic design people can make it in little time and think in a different ways.

"""Create a python dictionary for your name surname and year of birth."""

dict_eylemoyku = {'surname' : 'atalay' , 'birthdate' : '1992'}
print(dict_eylemoyku['surname'])
print(dict_eylemoyku['birthdate'])

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

surname = 'atalay'

if surname[0] == 'a' :
  print("my initial is a!")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

surname = 'atalay'
if len(surname)%3 == 0 :
  print("divisible")
else:
  print("not divisible")

"""Change your year of birth to 2678."""

dict_eylemoyku['birthdate'] = '2678'
print(dict_eylemoyku['birthdate'])

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""